// Generate src/schema.generated.ts from schema/wf2-schema.json (emitted by the C# `wf2 schema`
// command — the single source of truth). Run via `npm run gen`.
//
// The stable, human-facing ParamId for each parameter index lives here (not in C#), so renaming a
// parameter in the app never silently changes a public API id. If the app adds a new editable
// parameter, this script fails loudly until an id is added below.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const schema = JSON.parse(readFileSync(resolve(root, "schema/wf2-schema.json"), "utf8"));

/** paramIndex -> stable camelCase id (public API). */
const ID_BY_INDEX = {
  0: "brakingBalance",
  1: "brakingPressure",
  3: "frontDifferentialPower",
  4: "frontDifferentialPreload",
  14: "differentialPower",
  15: "differentialCoast",
  16: "differentialPreload",
  25: "antiRollBarFront",
  26: "frontCamber",
  27: "frontToe",
  33: "antiRollBarRear",
  34: "rearCamber",
  35: "rearToe",
  40: "gearboxFinalDrive",
  41: "gearboxGear1",
  42: "gearboxGear2",
  43: "gearboxGear3",
  44: "gearboxGear4",
  45: "gearboxGear5",
  46: "gearboxGear6",
  55: "ackerman",
};

const missing = schema.params.filter((p) => !(p.index in ID_BY_INDEX));
if (missing.length) {
  console.error(
    "gen-schema: no ParamId for parameter index(es): " +
      missing.map((p) => `${p.index} (${p.name})`).join(", ") +
      "\nAdd them to ID_BY_INDEX in scripts/gen-schema.mjs."
  );
  process.exit(1);
}

const ids = schema.params.map((p) => ID_BY_INDEX[p.index]);
const union = ids.map((id) => `  | ${JSON.stringify(id)}`).join("\n");

const entries = schema.params
  .map((p) => {
    const id = ID_BY_INDEX[p.index];
    const o = {
      id,
      index: p.index,
      name: p.name,
      min: p.min,
      max: p.max,
      steps: p.steps,
      storedUnit: p.storedUnit,
      displayUnit: p.displayUnit,
      displayFactor: p.displayFactor,
      confirmed: p.confirmed,
    };
    return `  ${id}: ${JSON.stringify(o)},`;
  })
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-schema.mjs from schema/wf2-schema.json.
// Do not edit by hand. Run \`npm run gen\` after re-emitting the schema with \`wf2 schema\`.

export const FORMAT_VERSION = ${schema.formatVersion} as const;

export type ParamId =
${union};

export interface ParamSchema {
  /** Stable, human-facing id (public API). */
  id: ParamId;
  /** The game's numeric parameter index — what is actually written to the save. */
  index: number;
  /** Display name, e.g. "Braking Balance". */
  name: string;
  /** Legal range and step count, in stored (SI) units. value = min + aux*(max-min)/steps. */
  min: number;
  max: number;
  steps: number;
  /** Unit the value is stored in ("" when unitless). */
  storedUnit: string;
  /** Unit the game's UI labels it with ("" when unitless). */
  displayUnit: string;
  /** Multiply the stored value by this to get the number the UI shows. */
  displayFactor: number;
  /** False when the parameter mapping is inferred rather than observed. */
  confirmed: boolean;
}

export const PARAMS: Record<ParamId, ParamSchema> = {
${entries}
};
`;

mkdirSync(resolve(root, "src"), { recursive: true });
writeFileSync(resolve(root, "src/schema.generated.ts"), out);
console.log(`gen-schema: wrote src/schema.generated.ts (${schema.params.length} parameters, format v${schema.formatVersion})`);
